name: build Rust on push

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Run_cargo_tests:
    name: Test rrss2imap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
#      - uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all-features

  Standard_OS_build:

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        # See https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
          - { os: ubuntu-18.04, name: rrss2imap_linux, path: target/debug/rrss2imap}
          - { os: macOS-10.15, name: rrss2imap_macOS, path: target/debug/rrss2imap}
          - { os: windows-2019, name: rrss2imap.exe, path: target/debug/rrss2imap.exe}
          # And this one is the dreaded Raspbian one ...
          - { os: ubuntu-18.04, name: rrss2imap_raspbian, path: target/armv7-unknown-linux-gnueabihf/debug/rrss2imap, target: armv7-unknown-linux-gnueabihf, linker: gcc-arm-linux-gnueabihf}
    steps:
      - name: Install linker
        run: sudo apt-get update &&  sudo apt-get install ${{matrix.config.linker}}
        if: matrix.config.linker!=null
      - name: Install libdbus-1-3
        # needed for the keyring crate on linux, see
        # https://github.com/diwic/dbus-rs#requirements
        run: sudo apt-get update && sudo apt-get install libdbus-1-dev pkg-config libdbus-1-3
        if: matrix.config.os=='ubuntu-18.04'
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{matrix.config.target}}
          override: true
        if: matrix.config.target!=null
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
        if: matrix.config.target==null
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          # temp
          args: --all-features
        if: matrix.config.target==null
      - uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: build
          args: --all-features --target ${{matrix.config.target}}
        if: matrix.config.target!=null
      - name: Upload build result for OS
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.config.name}}
          path: ${{matrix.config.path}}
    needs: Run_cargo_tests
