name: build Rust on push

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Run_cargo_tests:
    name: Test rrss2imap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  Standard_OS_build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: rrss2imap_linux
            path: target/debug/rrss2imap
          - os: macOS-latest
            name: rrss2imap_macOS
            path: target/debug/rrss2imap
          - os: windows-latest
            name: rrss2imap.exe
            path: target/debug/rrss2imap.exe
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Upload build result for OS
        uses: actions/upload-artifact@v1
        with:
          name: {{name}}
          path: {{path}}
    needs: Run_cargo_tests

  Cross_build:

    name: Build for Raspbian
    runs-on: ubuntu-latest

    steps:
      - name: Install linker
        run: sudo apt-get install -qq gcc-arm-linux-gnueabihf
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --all-features --target armv7-unknown-linux-gnueabihf
      - name: Upload build result for Raspbian
        uses: actions/upload-artifact@v1
        with:
          name: rrss2imap_armv7-unknown-linux-gnueabihf
          path: target/armv7-unknown-linux-gnueabihf/debug/rrss2imap
    needs: Run_cargo_tests
