name: build Rust on push

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Run_cargo_tests:
    name: Test rrss2imap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  Standard_OS_build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        include:
          - os: windows-latest
            target: i586-pc-windows-msvc
            name: rrss2imap_windows_i586.exe
            path: target/debug/rrss2imap.exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            name: rrss2imap_windows_i686.exe
            path: target/debug/rrss2imap.exe
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: rrss2imap_windows_x86_64.exe
            path: target/debug/rrss2imap.exe
          - os: macOS-latest
            target: i686-apple-darwin
            name: rrss2imap_apple_i686.exe
            path: target/debug/rrss2imap
          - os: macOS-latest
            target: x86_64-apple-darwin
            name: rrss2imap_apple_x86_64.exe
            path: target/debug/rrss2imap
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: rrss2imap_linux_x86_64
            path: target/debug/rrss2imap
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            name: rrss2imap_linux_armv7
            path: target/debug/rrss2imap
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "{{target}}"
          override: true
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --all-features
      - name: Upload build result for Raspbian
        uses: actions/upload-artifact@v1
        with:
          name: "{{name}}"
          path: "{{path}}"
