name: build Rust on push

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build and test rrss2imap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # see https://github.com/marketplace/actions/rust-cargo
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features