name: Create release on tag and dispatch to artifact push

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GITHUB_RELEASE: "undefined"
jobs:
  Make_GitHub_Release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Dispatch release for artifact upload
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: release_created
          client-payload: '{"upload_url": "${{ steps.create_release.outputs.upload_url }}", "ref": "${{ github.ref }}"}'